FROM openjdk
MAINTAINER Taner Diler <taner.diler@gmail.com>
ADD target/reactive-backoffice-0.0.1-SNAPSHOT.jar reactive-backoffice.jar
ENTRYPOINT ["java", "-jar", "/reactive-backoffice.jar"]
EXPOSE 2222